adapters/satori/package.json
adapters/satori/src/index.ts
adapters/satori/src/index_json_file.ts
adapters/satori/src/sdk/config.ts
adapters/satori/src/sdk/subgraphDetails.ts
adapters/satori/tsconfig.json

hi 
there are satori data at linea

satori tvl data

---

adapters/sparta/package.json
adapters/sparta/src/index.ts
adapters/sparta/src/sdk/config.ts
adapters/sparta/src/sdk/queries.ts
adapters/sparta/src/sdk/types.ts
adapters/sparta/src/sdk/utils.ts
adapters/sparta/tsconfig.json

support for tracking SpartaDEX pools:
| pool    | address  |
|----------|----------|
| USDC.e/USDT  |0x0460c78bd496ca8e9483e4f0655a28be1e90a89b |
| USDC.e/SPARTA     | 0x30CC8a4f62f1C89bF4246196901e27982be4FD30   |
| USDC.e/WETH | 0x51a056cc4eb7d1feb896554f97aa01805d41f190   |
| WETH/WBTC  | 0x38d4b2627ff87911410129849246a1a19f586873  |
| USDC.e/Gameswift     | 0x6a4d34cea32ecc5be2fc3ec97ce629f2b4c72334 |

added SpartaDEX support

---

adapters/deri/src/index.ts

update deri adapter

---

adapters/zerolend/src/index.ts

This adds the block number and timestamp to the data addressing issue #90

Added proper block numbers and used goldsky for zerolend addressing #90

---

adapters/mendi/src/index.ts
adapters/mendi/src/sdk/config.ts
adapters/mendi/src/sdk/marketDetails.ts
adapters/mendi/src/sdk/subgraphDetails.ts

Hi,
We updated the subgraph to a more performant version.
https://github.com/mendi-finance/subgraph
Now, creating csv rows takes like 5-6 mins.
Thanks,

feat: mendi finance subgraph performance

---

adapters/secta/src/sdk/config.ts

Checked all requirements for PR.
The only update is subgraph url in config file.
Previous urls were rate-limited.

Secta Finance: DEX: update to use production subgraph

---

adapters/clip-finance/src/index.ts
adapters/clip-finance/src/sdk/subgraphDetails.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

Clip.finance: yield: retry on too many request

---

adapters/secta/src/sdk/poolDetails.ts

In response to
https://t.me/c/2078068687/1/607

Secta Finance: Dex: fix error - skip empty v2 pools

---

adapters/syncswap/src/sdk/config.ts
adapters/syncswap/src/sdk/lib.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

syncswap: dex: update subgraph url to support Aqua Pool

---

adapters/connext/src/utils/subgraph.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

connext : interoperability : fix query for multiple hourly entries

---

adapters/myx/src/index.ts
adapters/myx/src/sdk/positionSnapshots.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

myx : dex : update

---

adapters/layerbank/src/sdk/marketDetails.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

fix: underlying addr type

---

adapters/layerbank/src/index.ts
adapters/layerbank/src/sdk/marketDetails.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

fix: lint contract getter null return err

---

adapters/layerbank/src/sdk/marketDetails.ts
adapters/layerbank/src/sdk/subgraphDetails.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

fix: lowercase for weth handling instead of zero address

---

adapters/xfai/src/index.ts

[xfai] export getUserTVLByBlock

---

adapters/myx/src/index.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

myx : dex : fix

---

adapters/davos/src/index.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

Davos: lending: fix lower case

---

adapters/nile/src/index.ts

* Fetch user votes in batches to avoid RPC errors

fix: fetch user votes in batches

---

adapters/satori/src/sdk/subgraphDetails.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

change the date to current block

---

adapters/satori/src/index.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

satori:fix the block_number match the time

---

adapters/clip_finance/src/sdk/subgraphDetails.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

ClipFinance: additional proxy strategy

---

adapters/overnight/src/sdk/config.ts

fix transfers err

---

adapters/teahouse/src/sdk/lib.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

fix the logic when query

---

adapters/dysonfinance/package.json
adapters/dysonfinance/src/index.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

Dyson Finance: add code snippets for readBlocksFromCSV

---

adapters/linehub/package.json
adapters/linehub/src/index.ts
adapters/linehub/src/sdk/config.ts
adapters/linehub/src/sdk/lib.ts
adapters/linehub/src/sdk/types.ts
adapters/linehub/tsconfig.json

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

linehub : dex : tvl by user

---

adapters/sturdy/src/sdk.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

sturdy: lending: tvl by user

---

adapters/lynex/src/sdk/config.ts

update subgraph for lynex
```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
```
token_symbol: string; //token symbol should be …
```

update subgraph link for lynex

---

adapters/qidao/src/index.ts

Updates job to track collateral instead of debt.

fix: now uses collateral tracking instead of debt tracking

---

adapters/interport/src/utils/client.ts

replace rpc
```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
```
token_symbol: string; //token symbol should be empty string if …
```

replace rpc for interport

---

adapters/zklink/src/protocols/novaswap/sdk/lib.ts
adapters/zklink/src/sdk/lib.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

zklink: other: update novaswap contract address

---

adapters/overnight/src/sdk/config.ts

fix config

---

adapters/connext/package.json
adapters/connext/src/utils/assets.ts
adapters/connext/src/utils/index.ts
adapters/connext/src/utils/rpc.ts
adapters/connext/src/utils/subgraph.ts
adapters/connext/yarn.lock

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

connext : bridge : use process.env var for RPC

---

adapters/logx/package.json
adapters/logx/tsconfig.json

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

logx:dex : tvl by user

---

adapters/linehub/src/index.ts
adapters/linehub/src/sdk/config.ts
adapters/linehub/src/sdk/lib.ts
adapters/linehub/src/sdk/types.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

linehub : dex : tvl by user - add trade tvl

---

adapters/linehub/src/index.ts
adapters/linehub/src/sdk/config.ts
adapters/linehub/src/sdk/lib.ts
adapters/linehub/src/sdk/types.ts

Reverts delta-hq/l2-lxp-liquidity-reward#248

Revert "linehub : dex : tvl by user - add trade tvl"

---

adapters/linehub/src/index.ts
adapters/linehub/src/sdk/config.ts
adapters/linehub/src/sdk/lib.ts
adapters/linehub/src/sdk/types.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

linehub : dex : tvl by user - add trade tvl 

---

adapters/logx/src/index.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

logx:dex: tvl by user

---

adapters/renzo/src/index.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

Renzo Protocol : TVL by user

---

adapters/logx/src/index.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

remove user level logging for logx

---

adapters/satori/src/sdk/config.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

satori: new graph

---

adapters/stargate/src/index.ts
adapters/stargate/src/sdk/config.ts
adapters/stargate/src/sdk/lib.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

stargate: bridge: add v2 positions

---

adapters/stargate/src/index.ts

Fixes an issue with downloading data from multiple blocks

stargate: bridge: fix: merge streams for multiple blocks

---

adapters/zerolend/src/index.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

Added missing pools for ZeroLend

---

adapters/gammastrategies/package.json
adapters/gammastrategies/src/config.ts
adapters/gammastrategies/src/index.ts
adapters/gammastrategies/src/types.ts
adapters/gammastrategies/tsconfig.json

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

gammastrategies: liquidity manager: tvl by user

---

adapters/renzo/src/index.ts

There's a breaking schema change in sentio entity tables.
Accordingly, updated underlying table from `AccountSnapshot` to `AccountSnapshot_raw`.
Also modified the query in more efficient manner.
```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
```
token_address: …
```

Renzo Protocol: update user tvl query

---

adapters/kelp_gain_linea/src/lib/pendle.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

kelp: gain : fix query tvl for pendle users 

---

adapters/zerolend/package.json
adapters/zerolend/src/index.ts
adapters/zerolend/src/sdk/foxy.ts
adapters/zerolend/src/sdk/lp.ts
adapters/zerolend/src/sdk/stake.ts
adapters/zerolend/src/sdk/tvl.ts
adapters/zerolend/yarn.lock

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

added rate limit for zerolend adapter

---

adapters/kelp_gain_linea/src/lib/spectra.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

kelp: gain : fix query for spectra users 

---

adapters/stargate/src/sdk/config.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

[linea] changing to private rpc for stargate

---

adapters/vfat/src/sdk/nile/lensDetails.ts
adapters/vfat/src/sdk/pancake/lib.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

increase delay in batch calls for vfat

---

adapters/stargate/src/sdk/config.ts
adapters/stargate/src/sdk/lib.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

[stargate] add delay , change rpc

---

adapters/stargate/src/index.ts

```export const getUserTVLByBlock = async (blocks: BlockData) => {
return csvRows
};
``` 
``` 
}
```
``` …
```

[stargate] fix adapter
